source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cardpay/ios-sdk-podspec.git'


platform :ios, '14'
use_frameworks!

target 'UnlimintSDKSwiftUI-Demo' do

  pod 'UnlimintSDK_SwiftUI',  '2.0.2'

end


post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
	            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
		end
	end
end
