source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cardpay/ios-sdk-podspec.git'


platform :ios, '14'
use_frameworks!

target 'UnlimintSDKSwiftUI-Demo' do

  pod 'UnlimintSDK_SwiftUI',  '2.0.7'

end


post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
	            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
              xcconfig_path = config.base_configuration_reference.real_path
              xcconfig = File.read(xcconfig_path)
              xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
              File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

		end
	end
end
